[[session]]
name = "Sesh"
path = "~/.config/sesh"
startup_command = "nvim sesh.toml"

[[session]]
name = "Tmux"
path = "~/.config/tmux"
startup_command = "nvim tmux.conf"

[[session]]
name = "Downloads"
path = "~/Downloads"
startup_command = "yazi"

[[session]]
name = "Home"
path = "~"

[[session]]
name = "repositories (c)"
path = "~/c"

[[session]]
name = "dotfiles"
path = "~/.local/share/chezmoi"

[[session]]
name = "Neovim"
path = "~/.config/nvim"
startup_command = "nvim"

[[session]]
name = "Configs"
path = "~/.config"
startup_command = "nvim"

[[session]]
name = "Hyprland"
path = "~/.config/hypr"
startup_command = "nvim"

[[session]]
name = "Omarchy"
path = "~/.local/share/omarchy/"
startup_command = "nvim"
