# -----------------------------------------------------------------------------
# Arrowlake Alacritty Colors
# Theme: Arrowlake Moon
# Upstream: https://github.com/jadonwb/arrowlake.nvim/raw/main/extras/alacritty/arrowlake_darker.toml
# -----------------------------------------------------------------------------

# Default colors
[colors.primary]
background = '#0D0C25'
foreground = '#c8d3f5'

# Normal colors
[colors.normal]
black = '#0a0a1e'
red = '#ff007c'
green = '#2A8669'
yellow = '#FFC066'
blue = '#3F3BF5'
magenta = '#DA4AB4'
cyan = '#61DDEE'
white = '#a9b1d6'

# Bright colors
[colors.bright]
black = '#312e55'
red = '#ff498a'
green = '#009672'
yellow = '#ffd29e'
blue = '#4f4cff'
magenta = '#fa40cc'
cyan = '#63edff'
white = '#c8d3f5'

[colors.cursor]
text = "#0a0a1e"
cursor = "#c8d3f5"

# [window]
# # Matching the opacity/blur of your Ghostty and Hyprland setup
# opacity = 0.73
# blur = true
